var h;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&document.documentElement.localName=="html"){window.__idm_init__=!0;typeof browser=="undefined"&&(browser=chrome);navigator.userAgent.includes("Edg/");navigator.userAgent.includes("OPR/");navigator.userAgent.includes("YaBrowser/");const V=Object.values,M=Array.from,N=Array.prototype.includes,I=Math.random,W=Function.call.bind(Array.prototype.slice),O=Function.apply.bind(Array.prototype.push),G=Function.call.bind(Array.prototype.forEach),X=
Function.apply.bind(String.fromCharCode,null),Y=Function.call.bind(String.prototype.charCodeAt),Z=String.fromCharCode,aa=["date","content-type","content-length"];function ba(a,b){return fetch(a,b).catch(()=>null)}function ca(a,b){b&&(a[b]=!0);return a}function B(a){return a.replace(/[a-z]/gi,function(b){return Z((b=Y(b))+((b&31)>13?-13:13))})}const da={16:!0,17:!0,18:!0,45:!0,46:!0},J=N.bind(["video","audio","object","embed"]),z=RegExp("(?!)"),ea=RegExp(" *\\$([<>{}|&*+=@!#%:?^~-])(\\d*) *"),fa=RegExp.prototype.test.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),
ha=globalThis,H=window.self===window.top;var C=window.origin||document.origin||location.origin,K=location,P=location.hostname.toLowerCase()+location.pathname+location.search;function Q(){browser.runtime.getFrameId?this.ma=browser.runtime.getFrameId(window):H&&(this.ma=0);this.Ia=[];this.na=[];this.Y=[];this.A={};this.kb();window.__idm_connect__=this.kb.bind(this,!0);this.j(1,window,"resize",this.Cc);this.j(1,window,"scroll",this.Dc);this.j(1,window,"blur",this.uc);this.j(1,window,"keydown",this.tb,
!0);this.j(1,window,"keyup",this.tb,!0);this.j(1,window,"mousedown",this.wc,!0);this.j(1,window,"mouseup",this.yc,!0);this.j(1,window,"mousemove",this.xc,!0);this.j(1,window,"click",this.vc,!0);this.j(1,document,"beforeload",this.sc,!0);this.j(1,document,"DOMContentLoaded",this.sb);document.readyState!="interactive"&&document.readyState!="complete"||this.sb()}h=Q.prototype;h.Ja="idmrs:///";h.va=z;h.v=0;h.C=0;h.oa=-1;h.pa=-1;h.zb=1;h.u="";h.$=0;h.m="";h.Pa="";h.M="";h.qa="";h.Wa=z;h.cb=RegExp(B('\\olgpst\\.frg\\(\\{(?=.*?"RKCREVZRAG_SYNTF":)(?=.*?"FGF":(\\q{5,})\\o|)(?=.*?"QNGNFLAP_VQ":"(.+?)"|)(?=.*?"YBTTRQ_VA":(\\j+)\\o|)(?=.*?"RBZ_IVFVGBE_QNGN":"(.+?)"|)(?=.*?"IVFVGBE_QNGN":"(.+?)"|)(?=.*?"CYNLRE_WF_HEY":"(.+?)"|)(?=.*?"FRFFVBA_VAQRK":"(\\q)"|)'),
"s");h.N=z;h.fb=z;h.Xa=z;h.I={};h.Ya="(?!)";h.Za="(?!)";h.$a=B('\\oshapgvba\\((\\j+)\\)\\{ine\\f+(\\j+)=[^?;,]*?(?:\\.fcyvg\\.\\j+\\(\\1,|\\1\\.fcyvg\\()(?:.+?\\ovs\\f*\\(glcrbs\\f+([\\j$]+)===?(([\\j$]+)[^()]+|"haqrsvarq")\\)\\f*erghea\\o)?.+?\\{erghea\\f+(?:([\\j$]+)\\[\\q+\\]|[^();,]+?)\\+\\f*\\1\\}\\f*erghea\\o[^{};]+?(?:\\.wbva\\.\\j+\\(\\2,|\\2\\.wbva\\o)[^{};]+?\\}');h.ab=B("(?<=\\oine\\f+)${3.3}=.+?(?=[;,}])");h.bb=B("(?<=\\oine\\f+)${3.5}=(([\"']).*?\\2\\.fcyvg\\(([\"']).\\3\\)|\\[(?:(?:\".*?\"|'.*?')(?:,\\f*|(?=\\])))+\\])(?=[;,])");
h.eb=B('$> *[ebyr="znva"]:abg(uvqqra) ivqrb, :fpbcr >qvi#cynlre ivqrb, lgzhfvp-cynlre ivqrb');h.gb=B("$> lgzhfvp-cynlre qvi#fbat-vzntr vzt");h.Va=B("$<< $> :fpbcr >ivqrb +qvi >pnainf");h.hb=B("$= lg.pbasvt_.RBZ_IVFVGBE_QNGN $= lgpst.qngn_.RBZ_IVFVGBE_QNGN $= lg.pbasvt_.IVFVGBE_QNGN $= lgpst.qngn_.IVFVGBE_QNGN");h.ua=z;h.ra=":root:empty";h.ta=0;h.sa=z;h.Aa=z;h.Ba='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';h.Da='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';
h.za='$+ article:scope, div.x1xfsgkm:scope $* main[role="main"] article, main[role="main"] >div >div.x1xfsgkm';h.Ea="$= poster $< <<<<<< $> div:scope >img:first-child, div[data-instancekey] div >img:first-child $= src";h.Ca=RegExp("/(?:p|reel|reels|stories/[\\w.-]+)/([\\w-]{11}|\\d{19})(?:[/?#]|$)");h.Qa=z;h.Ra=RegExp("^(?:[^/]+|player\\.vimeo\\.com/video)/(\\d{2,})");h.Ua="$| video:scope $| video";h.Sa="$> :scope >div.player";h.Ta="$& div.vp-video $& div.vp-telecine";h.kb=function(a){this.ub(-1);
this.g=a=browser.runtime.connect({name:(H?"top":"sub")+(a?":retry":"")+(location.protocol=="file:"?":file":"")});this.j(-1,a,"onMessage",this.Ac);this.j(-1,a,"onDisconnect",this.zc)};h.zc=function(){browser.runtime.lastError;this.ub();this.g=this.X=null;window.__idm_init__=!1;window.__idm_connect__=null};h.Ac=function(a){switch(a.shift()){case 11:this.Ub.apply(this,a);break;case 17:this.Vb.apply(this,a);break;case 12:this.Xb.apply(this,a);break;case 13:this.Wb=a.shift();break;case 14:this.$b.apply(this,
a);break;case 15:this.ac.apply(this,a);break;case 16:this.cc.apply(this,a);break;case 18:this.Zb.apply(this,a);break;case 19:this.bc.apply(this,a)}};h.Fc=function(a,b){var c=this.K>=105;let d=this.K>=108;switch(this.B=a){case 1:this.L=this.dc=!0;this.$=2;if(a=b.shift())this.m=a;if(a=b.shift())this.Wa=RegExp(a,"s");if(a=b.shift())this.N=RegExp(a);if(a=b.shift())this.fb=RegExp(a);if(a=b.shift())this.I=a.split(/[|:]/).reduce(ca,{});if(a=b.shift())this.Xa=RegExp(a);if(a=b.shift())this.Ya=a;if(a=b.shift())this.Za=
a;(a=b.shift())&&c&&(this.$a=a);(a=b.shift())&&c&&(this.ab=a);(a=b.shift())&&c&&(this.bb=a);(a=b.shift())&&d&&(this.cb=RegExp(a,"s"));(a=b.shift())&&d&&(this.eb=a);if(a=b.shift())this.Va=a;if(a=b.shift())this.Oa=a;if(a=b.shift())this.ec=a;if(a=b.shift())this.hb=a;if(a=b.shift())this.rc=a;if(a=b.shift())this.gb=a;break;case 2:this.mb();this.L=!0;this.$=3;if(a=b.shift())this.m=a;if(a=b.shift())this.M=a;if(a=b.shift())this.ua=RegExp(a);if(a=b.shift())this.Cb=a;if(a=b.shift())this.Fb=a;b.shift();if(a=
b.shift())this.ya=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Gb=a;if(a=b.shift())this.Bb=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.Fa=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Hb=a;if(a=b.shift())this.ra=a;if(a=b.shift())this.yb=a.startsWith("$")?a:`$* ${a}`;if(c=b.shift())this.ta=c;if(a=b.shift())this.Db=a;if(a=b.shift())this.sa=RegExp(a);break;case 4:this.mb();this.L=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Pa=a;if(a=b.shift())this.M=a;if(a=b.shift())this.Aa=
RegExp(a);if(a=b.shift())this.Mb=a;if(a=b.shift())this.Ba=a;if(a=b.shift())this.Da=a;if(a=b.shift())this.Nb=a;if(a=b.shift())this.za=a;if(a=b.shift())this.Jb=a;if(a=b.shift())this.Ga=a;if(a=b.shift())this.Ea=a;b.shift();if(a=b.shift())this.Kb=a;if(a=b.shift())this.Ca=RegExp(a);break;case 3:if(a=b.shift())this.Qa=RegExp(a);if(a=b.shift())this.Ra=RegExp(a);if(a=b.shift())this.Ua=a;if(a=b.shift())this.Sa=a;if(a=b.shift())this.Ta=a;break;case 5:this.L=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.M=
a;if(a=b.shift())this.Ob=a;break;default:this.L=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Na=a}this.m.includes("^/")&&((b=this.Pa)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=C.replaceAll(".","\\."),this.m=this.m.replaceAll("^/",`^(?:${b})?/`))};h.ha=function(a){if(this.B&&this.U(arguments))switch(this.B){case 1:this.qc(a);break;case 2:this.lc(a);break;case 4:this.mc(a);break;case 3:this.oc(a);break;case 5:this.nc(a)}};h.da=function(a){let b=this.g;for(let c of document.getElementsByTagName("script"))!c.src&&
a.test(c.text)&&b.postMessage([34,null,-1,c.text]);b.postMessage([34,this.D()])};h.ka=function(a,b,c,d){if(this.Ab&&c){let e=a instanceof Element?this.S(a):0,g=this.Y,f=g.indexOf(null);f<0&&(f=g.length);g[f]=[a,b,d];this.la(1229212981,f,e,c)}else d(a,b)};h.Bc=function(a,b){var c=this.Y.splice(a,1,null).shift();if(c){a=c[0];let d=c[1];c=c[2];a instanceof Element&&!document.contains(a)&&(b=void 0);c(a,d,b)}};h.Ec=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==C)switch(b[0]){case 1229212977:this.Ab=
!0;a=btoa(I().toString().substr(2,9));b=btoa(I().toString().substr(2,9));this.la(1229212978,this.X,this.u,a,b,aa,this.qa,this.L,this.dc,this.m,this.M);break;case 1229212979:this.g.postMessage([46,b[1],b[2],b[3]]);break;case 1229212980:this.g.postMessage([36,b[1],b[2]]);break;case 1229212982:this.Bc(b[1],b[2])}};h.la=function(a,...b){window.postMessage(W(arguments),"/")};h.ea=function(){let a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};h.mb=function(){this.u||
(this.u=btoa(I().toString().substr(2,9)))};h.S=function(a){let b,c=a.l;c||(c=a.l=this.X<<13|this.zb++,this.A[c]=a,(b=this.u)&&a.setAttribute(b,c));return c};h.P=function(a){let b=this.u,c=this.A;b&&a.removeAttribute(b);this.h&&(a.removeAttribute("__idm_uri__"),a.removeAttribute("__idm_obs__"));a.G&&(window.clearTimeout(a.G),a.G=null);a.F&&(a.F.disconnect(),a.F=null);this.Z.unobserve(a);this.V.unobserve(a);delete c[a.l];delete c[a.o];delete c[a.i];a.l=a.o=a.i=a.J=a.T=null};h.ib=function(a,b,c,d,e){let g=
this.A,f=this.S(a);if(b||c){if(b&&g[b]||c&&g[c])return;d||=a.localName;a.o=b;a.i=c||=`${this.Ja}${d}/${b}`;b&&(g[b]=a);c&&(g[c]=a);this.h&&a.setAttribute("__idm_uri__",c)}a.F||(b=a.F=new MutationObserver(this.W.bind(this)),this.h&&a.setAttribute("__idm_obs__",1),b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.Z.observe(a),e&&this.V.observe(a));this.B==1&&r(a,this.Oa)&&(a.fa=!0,a.fc=10);return f};h.H=function(a,b,c,d,e){if(b=this.ib(a,b,c,d,e))c=
this.R(a),this.g.postMessage([41,b,a.localName,a.src||a.data,a.i,a.o,c])};h.jb=function(a,b,c){if(!a.l&&b.l){this.h&&a.setAttribute("__idm_uri__",b.i);a.T=new WeakRef(b);b.T=new WeakRef(a);if(!a.F){let d=a.F=new MutationObserver(this.W.bind(this));this.h&&a.setAttribute("__idm_obs__",1);d.observe(a,{attributes:!0,attributeFilter:["style"]});d.observe(a.parentElement,{childList:!0});this.Z.observe(a)}this.V.observe(a);this.V.observe(b);c&&this.wb(a,b)}};h.Ib=function(a){if(!a.l){var b=a.T;b&&((b=b.deref())?
this.wb(a,b):a.T=null)}};h.wb=function(a,b){let c=this.u,d=this.A,e=a.l=b.l,g=a.o=b.o,f=a.i=b.i;b.l=b.o=b.i=null;c&&b.removeAttribute(c);c&&a.setAttribute(c,e);d[e]=a;g&&(d[g]=a);f&&(d[f]=a)};h.Tb=function(a,b,c,d,e,g){let f,k,l,p;let n,m,t=window.getComputedStyle.bind(window);try{let v=0;l=document.activeElement;l&&J(l.localName)||(l=document.elementFromPoint(this.oa,this.pa))&&!J(l.localName)&&(l=null);for(let q of document.querySelectorAll("video,audio,object,embed")){let D=q.localName,x;var w=
D=="object"||D=="embed";if(w){let F=q.type.toLowerCase();if(F.startsWith("text/")||F.startsWith("image/"))continue;if(D=="embed"&&F!="application/x-shockwave-flash")continue}if(q.i&&!q.fa&&(e||g))if(e?e==q.o:g==q.i)f=q;else continue;else if(x=q.src||q.data)x!=a&&x!=b||(f=q);else if(!w)for(let F of q.getElementsByTagName("source"))if((x=F.src)&&(x==a||x==b)&&(f=q))break;if(f)if(t(q).objectFit=="cover")k=q,f=null;else break;if(k||l||p)continue;if(x){if((x==c||x==d)&&(p=q))continue;if(D=="video"&&x.startsWith("data:audio/"))continue}let A=
q.clientWidth,y=q.clientHeight;if(!A||!y)continue;let R=q.getBoundingClientRect();if(R.right+window.scrollX<=0||R.bottom+window.scrollY<=0)continue;let S=t(q);if(q.J||S.visibility=="hidden"||S.display=="none"){D=="video"&&(m||=q);continue}w=A*y;if(v<w&&A*1.35>y&&A<y*3){v=w;var u=q}n||=q}}catch(v){}(a=f||k||l||p)?a.localName!="video"&&t(a).visibility=="hidden"&&(a=null):a=u||n||m;a&&(a.localName!="embed"||a.clientWidth||a.clientHeight||(u=a.parentElement,u.localName=="object"&&(a=u)),this.ib(a,e,g));
return a};h.Sb=function(a,b,c){let d=null,e,g=browser.runtime.getFrameId;for(let f of document.getElementsByTagName("iframe")){let k=f.pb;k==null&&g&&(k=f.pb=g(f));if(k==a){d=f;break}else d||!(e=f.src)||e!=b&&e!=c||(d=f)}return d&&this.S(d)};h.R=function(a){let b=null;try{let c=window.getComputedStyle(a),d=a.getBoundingClientRect(),e=this.$,g=Math.round(d.width),f=Math.round(d.height),k;if(c.visibility=="hidden"&&!a.contentWindow)return g>f*5?null:!1;if(c.opacity==0||a.J)return!1;if(this.B==1&&a.offsetTop+
a.offsetHeight==0){for(let u=a;u=u.parentElement;){let v=window.getComputedStyle(u);if(v.display!="block")break;if(v.opacity==0)return!1}d=a.parentElement.parentElement.getBoundingClientRect();e=0;c.display=="none"&&r(a,this.Va)&&(g=Math.round(d.width),f=Math.round(d.height))}let l=Math.round(d.left)+a.clientLeft,p=Math.round(d.top)+a.clientTop;for(let u=0,v=0,q=a,D=c,x,A;e--&&D.display=="block"&&(x=q.parentElement)&&x.localName=="div";q=x,D=A){A=window.getComputedStyle(x);u-=q.offsetLeft;v-=q.offsetTop;
if(A.overflowX=="hidden"){let y=g-x.offsetWidth-u;u>0&&(g-=u,l+=u);y>0&&(g-=y);e=0}if(A.overflowY=="hidden"){let y=f-x.offsetHeight-v;v>0&&(f-=v,p+=v);y>0&&(f-=y);e=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.i||a.readyState<1&&a.networkState==2)&&(b=!1);if(g<15||f<10)return b;break;case "audio":if(g<1&&f<1)return b;k=!0}let n=document.documentElement,m=n.scrollWidth||n.clientWidth||document.body.scrollWidth,t=n.scrollHeight||n.clientHeight||document.body.scrollHeight;
if(l>=m||p>=t||k&&!l&&!p)return b;l==0&&p==-t&&g==m&&f==t&&(p=0);let w=a.fc||0;b=[l,p+w,l+g,p+f-w,this.ea()]}catch(c){}return b};h.Lb=function(a){var b=a.hc;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){let e=window.getComputedStyle(c);if(e.visibility=="visible"&&e.opacity!="0"&&!fa(e.backgroundColor)){d=!0;break}}a.J=d}};h.D=function(){let a=H?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&
b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};h.Yb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement;let b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0);let d=0,e=0,g=0;for(let k of c)if(k.offsetWidth>=b){var f=window.getComputedStyle(k);f.opacity>=.95&&(c=f.zIndex,f.position=="fixed"?(f=k.offsetHeight+k.offsetTop,
d<f&&f<a&&(d=f,e=c)):g<c&&(g=c))}e<g&&(d=0);return d};h.Ub=function(a,b,c,d,e,g,f,k,l,p,n,m,...t){this.K=a;this.X=b;if(n||=K.hostname.toLowerCase().split(".").at(-2))this.va=RegExp(`^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*${n}$`,"i"),this.Ja=`idmrs://${n}/`;if(d){this.ma=d;try{window.frameElement&&(window.frameElement.pb=d)}catch(w){}}this.ob(g);l&&(this.qa=l);e&&this.Fc(e,t);p&&(ha.idm=this,this.h=!0,this.u="__idm_id__",T("text/javascript",p));m&&(this.j(2,window,"message",this.Ec),T("text/javascript",
m));document.readyState=="loading"?this.Ka=!0:this.ha()};h.Vb=function(a){P=location.hostname.toLowerCase()+location.pathname+location.search;this.La&&this.v&&(this.v=0,this.Ma=window.setTimeout(this.ja.bind(this,!1),3E3));this.ha(!0);a&&this.ob();for(let b of new Set(V(this.A)))this.Lb(b)};h.bc=async function(a,b,c,d,e,g){let f=new Headers,k=AbortSignal.timeout(1E7);d={method:d,headers:f,body:g,signal:k,priority:"high",cache:"force-cache"};if(e&&e.length){for(let p of e)f.append(p.name,p.value);
f.has("referer")&&(d.referrer=f.get("referer"))}f.has("accept")||f.append("accept","*/*");f.append("accept",`application/vnd.t1c.int-${a}`);c=await ba(c,d);let l;c&&c.status==200&&(b<0?(b=await c.arrayBuffer(),b=X(b instanceof ArrayBuffer?new Uint8Array(b):b)):b=await c.text(),l=b);this.g.postMessage([45,a,l])};h.ob=function(a){if(this.U(arguments)){var b=[21,K.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.g.postMessage(b)}};
h.$b=function(a){var b=a?this.U(arguments):1;if(b>0||b<0&&this.B!=1){b=this.D();let c=this.ea(),d=this.Yb();this.g.postMessage([24,b,b&&b.src,c,d])}};h.cc=function(a,b,c,d,e){c||=this.Sb(b,d,e);d=(d=c&&this.A[c])&&this.R(d);this.g.postMessage([22,a,b,c,d])};h.Zb=function(a,b){let c,d,e=document.getElementsByTagName("a");for(let g of e)try{if(g.href==b){c=g.download||null;d=g.innerText.trim()||g.title||null;break}}catch(f){}this.g.postMessage([35,a,c,d])};h.ac=function(a,b,c,d,e,g,f,k){if(this.U(arguments)){var l=
[23,a,b,!1],p,n;var m=this.A;if(b)(m=m[b])||(l[3]=!0);else{m=k&&m[k]||f&&m[f];if(!m||m.fa)m=this.Tb(c,d,e,g,k,f);if(m){if(this.Na&&(p=r(m,this.Na)))var t=200;else if(p=m.getAttribute("operadetachedviewtitle"))t=130;l[2]=b=m.l;l[5]=m.localName;l[6]=m.src||m.data}else if(k||f)l[3]=!0;!p&&(p=this.D())&&(t=p.src,(n=this.va.exec(p))&&(p=n[1]));l[7]=p;l[8]=t}if(m)if(p=this.R(m),p!=null||document.contains(m)){if(l[4]=p,a&&this.B==1&&this.ba)try{l[9]=window.sessionStorage.getItem(this.ba)}catch(w){}}else this.P(m),
l[3]=!0;this.g.postMessage(l)}};h.Xb=function(a,b,c,d){let e=d?RegExp(d,"i"):null;d=this.nb(document,e,b);let g=document.getElementsByTagName("iframe");for(let f of g)try{let k=f.contentDocument;k&&!f.src&&O(d,this.nb(k,e,b))}catch(k){}a=[27,a,this.ma,d.length];c||(a[4]=d,a[5]=K.href,H&&(a[6]=K.href,a[7]=document.title));this.g.postMessage(a)};h.nb=function(a,b,c){let d=[],e={};var g="";let f="",k=!c,l;if(c&&(l=a.getSelection(),!l||l.isCollapsed&&!l.toString().trim()))return d;for(let n of a.getElementsByTagName("a"))if(k||
l.containsNode(n,!0))try{let m=n.href;m&&!e[m]&&b.test(m)&&(e[m]=d.push([m,2,n.download||null,n.innerText.trim()||n.title]));c&&e[m]&&(f+=n.innerText,f+="\n")}catch(m){}for(let n of a.getElementsByTagName("area"))if(k||l.containsNode(n,!0))try{let m=n.href;m&&!e[m]&&b.test(m)&&(e[m]=d.push([m,2,null,n.alt]))}catch(m){}for(let n of a.getElementsByTagName("img"))if(k||l.containsNode(n,!0))try{let m=n.src;m&&!e[m]&&b.test(m)&&(e[m]=d.push([m,3,null,`<<<=IDMTRANSMITIMGPREFIX=>>>${n.alt}`]));k&&n.onclick&&
(g+=n.onclick,g+="\n")}catch(m){}if(c){if(g=l.toString()){c=this.O(f);for(var p of this.O(g))p&&!e[p]&&b.test(p)&&!c.includes(p)&&(e[p]=d.push([p,1]))}for(let n of a.getElementsByTagName("textarea"))if(a=n.selectionStart,g=n.selectionEnd,(p=l.isCollapsed&&a<g)||l.containsNode(n,!0))try{let m=p?n.value.substring(a,g):n.value;for(let t of this.O(m))t&&!e[t]&&b.test(t)&&(e[t]=d.push([t,1]))}catch(m){}}else{for(let n of a.getElementsByTagName("iframe"))try{let m=n.src;m&&!e[m]&&b.test(m)&&(e[m]=d.push([m,
4]))}catch(m){}for(let n of a.getElementsByTagName("script"))g+=n.innerText,g+="\n";if(g)for(let n of this.O(g))n&&!e[n]&&b.test(n)&&(e[n]=d.push([n,5]))}return d};h.O=function(a){if(!this.Ha){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\- -﻿","%T":"\\w\\-.+*()$!,% -﻿","%Q":"^\\s\\[\\]{}()"}));this.Ha=RegExp(b,"gi")}let c=[];for(;b=this.Ha.exec(a);)c.push(b.shift());
return c};h.U=function(a){let b=this.v;b||(a=M(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.na.push(a));return b};h.sb=function(a){let b;try{b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.v=a&&b?-1:1;b&&(a=this.La,a||(a=this.La=new MutationObserver(this.ja.bind(this))),a.observe(b,{childList:!0}),this.h&&b.setAttribute("__idm_obs__",1));this.Z=new ResizeObserver(this.W.bind(this));this.V=new IntersectionObserver(this.W.bind(this),{threshold:.2});this.Ka&&
(this.Ka=!1,this.ha());for(let c,d=this.na;c=d.shift();)c.shift().apply(this,c)};h.W=function(a){if(this.g)for(let b of a)if(b.target.l)if(a=b.target,a.isConnected){let c=b.isIntersecting;if(c!=null){let d=a.J;a.J=!c;a.hc=c?b.intersectionRect:null;c&&d&&this.Ib(a)}a.G&&window.clearTimeout(a.G);a.G=window.setTimeout(this.tc.bind(this,a),200)}else this.g.postMessage([23,null,a.l,!0]),this.P(a)};h.tc=function(a){if(!this.g)return this.P(a);a.G=null;let b=document.contains(a),c;if(b){if(c=this.R(a),this.B==
1&&a.fa)if(c){let d=r(a,this.Oa);d?.href&&d.href!=a.i&&this.H(a,null,d.href)}else a.i=a.o=null,b=!1}else this.P(a);this.g.postMessage([23,null,a.l,!b,c])};h.ja=function(a){if(a)window.clearTimeout(this.Ma),this.Ma=window.setTimeout(this.ja.bind(this,!1),1E3);else{this.v<0?this.v=1:++this.v;for(let b,c=this.na;b=c.shift();)b.shift().apply(this,b)}};h.sc=function(a){var b=a.target;let c=b.localName;J(c)&&a.url&&(b=this.S(b),this.g.postMessage([25,b,c,a.url]))};h.tb=function(a){!a.repeat&&da[a.keyCode]&&
this.g.postMessage([31,a.keyCode,a.type=="keydown"])};h.wc=function(a){this.Wb&&this.g.postMessage([28]);if(a.button==0){let b=a.view.getSelection();b?.isCollapsed&&!b.toString().trim()&&(this.C=1);this.g.postMessage([32,a.button,!0])}};h.yc=function(a){if(a.button==0){this.oa=a.clientX;this.pa=a.clientY;this.g.postMessage([32,a.button,!1]);let b=a.view.getSelection();b&&this.C&&(this.C=b.isCollapsed&&!b.toString().trim()?0:2)&&this.g.postMessage([26,a.clientX,a.clientY,this.ea()])}};h.xc=function(){this.C==
2&&(this.C=0)};h.vc=function(a){a=a.target;a.localName=="a"&&this.g.postMessage([39,a.hasAttribute("download"),a.href,a.download])};h.Dc=function(){this.g.postMessage([29])};h.Cc=function(a){a=a.target;this.g.postMessage([30,a.innerWidth,a.innerHeight])};h.uc=function(){this.C=0;this.g.postMessage([33])};h.j=function(a,b,c,d,...e){e=M(arguments);e[3]=d.bind(this);this.Ia.push(e);a<0?(b=b[c],b.addListener.apply(b,e.slice(3))):b.addEventListener.apply(b,e.slice(2))};h.ub=function(a){let b=this.Ia;for(let c=
0;c<b.length;c++){let d=b[c][0];if(a&&a!=d)continue;let e=b.splice(c--,1).pop(),g=e.splice(0,2).pop();d<0?(g=g[e.shift()],g.removeListener.apply(g,e)):g.removeEventListener.apply(g,e)}};h.qc=function(a){this.aa&&(window.clearTimeout(this.aa),this.aa=null);var b=this.fb.exec(K.pathname+K.search);b&&this.xb(b[1]);if(!a){this.la(1229212983,this.rc);var c,d;a=0;for(var e of document.getElementsByTagName("script")){if(e.src){if(b=this.N.exec(e.src))a|=1,this.I[b[1]]?d=b[1]:c=e.src}else if(b=this.cb.exec(e.text)){a|=
2;var g=b[1]&&parseInt(b[1],10);var f=b[2];var k=b[3]=="true";var l=b[4]||b[5];var p=b[7]&&parseInt(b[7],10);if(b=this.N.exec(b[6]))this.I[b[1]]?d=b[1]:c||=C+b[0]}else if(this.Wa.test(e.text)){a|=4;var n=e.outerHTML}if(a==7)break}b=this.K>=101;e=this.K>=105;(a=k?f:l)?this.ba=U(a):this.ka(window,k||!b?136:138,k?this.ec:this.hb,this.Hc.bind(this));if(d||g||f||l||p||k!=null)var m={[124]:d,[144]:c,[118]:g,[136]:k||b?f:l,[138]:l,[143]:p,[139]:k};c&&e?(d=new XMLHttpRequest,d.responseType="text",d.timeout=
1E4,d.onreadystatechange=this.Ic.bind(this,c,m,n,d),d.open("GET",c,!0),d.send()):(m&&this.g.postMessage([37,1,2,m]),n&&this.g.postMessage([34,this.D(),null,n]))}};h.xb=function(a,b,c){let d=!b;d&&(b=r(document.body,this.gb));let e=r(document.body,this.eb),g=!!e?.offsetWidth,f=!g&&b||e;f&&d&&this.H(f,a,null,"video");e&&b&&e!==b&&(d&&g?this.jb(b,e):this.jb(e,b,g));!e&&(c||=0)<10&&(this.aa=window.setTimeout(this.xb.bind(this,a,b,++c),500))};h.Ic=function(a,b,c,d){if(d.readyState==4){var e=d.response,
g=this.N.exec(a);a=this.Xa.exec(e);var f=g&&g[1],k=a&&parseInt(a[1]||a[2],10);if(k&&(!this.I[k]||!this.I[f])){a=[null,119,120,135,141,142];g=[null,this.Ya,this.Za,this.$a,this.ab,this.bb];d={[118]:k,[124]:f,[144]:d.responseURL};let l=[];f=!0;for(k=0;f&&++k<g.length;){let p=g[k];k>1&&(p=p.replace(/\$\{(\d+)\.(\d+)\}/g,(n,m,t)=>l[m][t].replaceAll("$","\\$")));try{f=l[k]=RegExp(p,"s").exec(e)}catch(n){f=null}}if(k>=3){for(e=1;e<a.length;e++)l[e]&&(d[a[e]]=l[e][0]);this.g.postMessage([37,1,1,d])}else this.K>=
110&&(d[140]=e,this.g.postMessage([37,1,4,d]))}b&&this.g.postMessage([37,1,2,b]);c&&this.g.postMessage([34,this.D(),null,c])}};h.Hc=function(a,b,c){c&&(this.ba=U(c),this.g.postMessage([37,1,2,{[b]:c}]))};function U(a){let b=0,c=6038198,d=0,e;for(e=a.length>>1;b<e;b++)c=c*31+a.charCodeAt(b)|0;for(e=a.length;b<e;b++)d=d*31+a.charCodeAt(b)|0;return c.toString(16)+d.toString(16)}h.lc=function d(b,c){b?(c&&b.shift().disconnect(),this.ia.disconnect(),this.xa.disconnect(),this.wa.clear()):(this.da(this.ua),
this.ia=new MutationObserver(this.Qb.bind(this)),this.xa=new MutationObserver(this.Pb.bind(this)),this.wa=new Set);if(c=this.Eb=r(document.body,this.Fb)){if(b=this.ia,b.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","P"),!this.lb(c,!0)&&(c=r(c,this.Gb))){var e=r(c,this.ya);e?(b.observe(e,{childList:!0}),this.h&&e.setAttribute("__idm_obs__","P"),b.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","P")):(b.observe(c.parentNode,{childList:!0}),this.h&&c.parentNode.setAttribute("__idm_obs__",
"P"))}}else!b&&(c=r(document.body,this.Cb))&&(e=new MutationObserver(d.bind(this,b=[])),b.push(e),e.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","R"))};h.lb=function(b,c){let d=this.ia,e=this.ya,g=this.Bb,f=this.xa,k=this.wa,l=0;for(let p of r(b,g,[]))k.has(p)||r(p,g)||(k.add(p),f.observe(p,{childList:!0,subtree:!0}),this.h&&p.setAttribute("__idm_obs__","M"),c&&(b=r(p,e))&&(l++,d.observe(b,{childList:!0}),this.h&&b.setAttribute("__idm_obs__","P")),G(p.getElementsByTagName("video"),
this.ca.bind(this)));return l};h.Qb=function(b){let c=this.Eb;for(let d of b){b=d.target.isSameNode(c);for(let e of d.addedNodes)e.nodeType==1&&this.lb(e,b)}};h.Pb=function(b){let c=this.Y,d=this.Fa;for(let e of b)for(let g of e.addedNodes)if(g.nodeType==1)if(b=g.getElementsByTagName("video"),b.length)G(b,this.ca.bind(this));else for(let f of c)if(f){b=f[0];let k=r(b,d);k&&k.contains(g)&&this.ca(b,!0)}};h.ca=function(b,c){if(!b.i){var d=r(b,this.Fa),e=d&&r(d,this.Hb);if(!e){let k=this.ra,l=this.ta,
p=N.bind(["div","span","a"]),n,m,t,w,u;for(let v=d;v&&l--&&p(v.localName);v=v.parentNode){m=v;let q;var g=v;var f=`${k}:scope:first-child:only-of-type`;for(q=0;f[q]=="<";q++);q&&(f=f.slice(q));for(g=g.closest(f);g&&q--;g=g.parentElement);if(g)break;if((t=v.previousSibling)&&t.localName=="div"){n||=v.querySelector('div[role="slider"]');(u=v.querySelectorAll(k)).length==1?g=u[0]:(w=v.nextSibling)&&(u=w.querySelectorAll("ul:scope "+k)).length==1?g=u[0]:n&&(u=t.querySelectorAll(k)).length>1&&(g=u[u.length-
1]);break}}!g&&m&&(u=r(m,this.yb,[])).length==1&&(g=u[0]);!g&&d&&(g=d.querySelector(`:scope >${k}`));g&&(g=g.href);!g&&document.getElementsByTagName("video").length==1&&(e=this.sa.exec(K.href))&&(e=e[1])}e||g?this.H(b,e,g):c||this.ka(b,0,this.Db,this.Rb.bind(this))}};h.Rb=function(b,c,d){d&&this.H(b,d)};h.mc=function(b){!b&&(this.da(this.Aa),b=r(document.body,this.Mb))&&(E(b,this.Ba,this.jc.bind(this)),E(b,this.Da,this.ga.bind(this)),E(b,this.Nb,this.ga.bind(this)),E(document.body,this.Jb,this.ga.bind(this)))};
h.qb=function(b,c,d){!c&&document.getElementsByTagName("video").length==1&&(c=this.Ca.exec(K.href))&&(c=c[1]);this.H(b,c,d,"video",!0)};h.jc=function(b){for(let c of r(b,this.za,[]))G(r(c,this.Ga,[]),this.rb.bind(this))};h.ga=function(b){G(r(b,this.Ga,[]),this.rb.bind(this))};h.rb=function(b){if(!b.i){var c=r(b,this.Ea);c?this.qb(b,null,c):this.ka(b,0,this.Kb,this.kc.bind(this))}};h.kc=function(b,c,d){d&&this.qb(b,d)};h.oc=function(b){b||(this.da(this.Qa),(b=r(document.body,this.Sa))&&E(b,this.Ta,
this.Gc.bind(this)))};h.Gc=function(b){if(b=r(b,this.Ua)){let c=this.Ra.exec(P);c&&this.H(b,c[1])}};h.nc=function(b){if(!b){var c=r(document.body,this.Ob);c&&(b=this.D(),c=c.outerHTML,this.g.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function T(b,c){b=document.createElement(b.startsWith("image/")?"img":"script");b.src=browser.runtime.getURL(c);b.onload=b.remove.bind(b);document.documentElement.appendChild(b)}function r(b,c,d){function e(m,t,w){for(;w&&t--;)w=w.parentElement;w&&(isNaN(m)||
this.push(m),this.push(w));return w}if(!c)return d;let g,f,k,l=!0,p=d||[],n=c.split(ea);for(n.length==1?n.unshift(">",NaN):n.shift();b&&(g=n.shift());){c=parseInt(n.shift(),10);f=n.shift().trim();for(k=1;f[f.length-k]=="<";k++);--k&&(f=f.slice(0,-k).trim());switch(g){case "<":b=L(f?b.closest(f):b,k);l=!0;break;case ">":b=L(b.querySelector(f),k);l=!0;break;case "{":b.closest(f)&&(b=null);break;case "}":b.querySelector(f)&&(b=null);break;case "|":if(f=f.endsWith(":scope")?b.closest(f):b.querySelector(f))return L(f,
k);l=!1;break;case "&":b=e.call(p,c,k,b.querySelector(f));l=!1;break;case "*":b.querySelectorAll(f).forEach(e.bind(p,c,k));l=!1;break;case "+":f=f?f.endsWith(":scope")?b.closest(f):b.querySelector(f):b;e.call(p,c,k,f);l=!1;break;case "=":if(f=b.getAttribute(f))return f;l=!1;break;case "@":if(f=b.textContent.trim())return f;l=!1}}return p.length?p:l&&b||d}function E(b,c,d,e,g,f){if(e==null){e=r(b,c,[]);f=new MutationObserver(E.bind(null,b,c,d,e));f.observe(b,{childList:!0});this.h&&b.setAttribute("__idm_watch__",
1);this.h&&e.forEach(l=>l.setAttribute("__idm_watch__",1));for(var k of e)f.observe(k,{childList:!0});e.length&&d(e.at(-1))}else for(let l of g){for(let p of l.addedNodes)if(p.nodeType==1)if(g=r(b,c,[]).slice(e.length),(k=g.at(-1))&&p.contains(k)){O(e,g);this.h&&g.forEach(n=>n.setAttribute("__idm_watch__",1));for(let n of g)f.observe(n,{childList:!0});for(let n of k.children)d(n)}else l.target.isSameNode(e.at(-1)||b)&&d(p);for(let p of l.removedNodes)if(p.nodeType==1)for(g=0;g<e.length;g++)if(p.contains(e[g])){e.splice(g);
break}}}function L(b,c){for(;b&&c--;b=b.parentElement);return b}new Q}!0;
