(function(){function pa(c){let a=5381,b=c.length;for(let d=0;d<b;d++)a=a*33+c.charCodeAt(d)>>>0;return a}function qa(c,a){m.apply(this,arguments);try{if(G.test(a)){let b=this[P],d=`${H}-${++ra}`;b[I]=d;this.addEventListener(sa,Da.bind(this,d))}}catch(b){}}function Ea(c,a){try{let b=this[P];b[I]&&c.toLowerCase()==u&&(b[Q]=!0)}catch(b){}q.apply(this,arguments)}function Fa(c){try{let a=this[P],b=a[I];if(b){let d=a[Q];delete a[Q];delete a[I];d||q.call(this,u,ca);q.call(this,u,`${da}.pxr-${b}`)}}catch(a){}v.apply(this,
arguments)}function Da(c){try{if(c){let a=this[ta],b=ea.exec(a);w([1229212980,c,b&&(b[1]||a)||null],"/")}}catch(a){}}function fa(c,a){let b,d;var e;try{let f=R(c);if(b=G.test(f?c[S]:c))d=`${H}-${++ra}`,f?e=c[x]:a?e=a[x]:a=arguments[1]={},e||=a[x]=new p[ha],e.has(u)||e.append(u,ca),e.append(u,`${da}.pfm-${d}`)}catch(f){}e=n.apply(this,arguments);try{if(b)return e.then(Ga.bind(this,d))}catch(f){}return e}function Ga(c,a){try{if(c)if(a.ok&&a[k]){let b=a.constructor.prototype;a[r]=function(){return b[r].call(this).then(J.bind(null,
c,1))};a[y]=function(){return b[y].call(this).then(J.bind(null,c,2))};a[k][K]=function(e){return d(c,this)[K](e)};a[k][ia]=function(e,f){return d(c,this)[ia](e,f)};function d(e,f){if(f[k]===!0)return f;let [g,z]=f[ja](),T=z[K]();f[k]=!0;T[U]().then(ka.bind(T,e,[]));return g}}else w([1229212980,c],"/")}catch(b){}return a}function ka(c,a,b){b.done?J(c,1,a.join("")):(a.push(V(b.value,ua)),this[U]().then(ka.bind(this,c,a)))}function va(){return L(1,t,this,arguments)}function Ha(){return L(2,A,this,arguments)}
function Ia(){return L(3,B,this,arguments)}function Ja(){return L(4,C,this,arguments)}function Ka(){return L(5,D,this,arguments)}function L(c,a,b,d){a=a.apply(b,d);try{let e=b[S];if(e&&G.test(e)){let f=la.map(ma[E].bind(b[x]));f.unshift(e);let g=pa(f.join("|"));a=a.then(J.bind(null,`${H}-${g}`,c))}}catch(e){}return a}function La(){let c,a;try{c=this[x],a=c[k]}catch(d){}if(a===void 0&&(a=F.apply(this,arguments)))try{var b=this[S];if(b&&G.test(b)){let d=la.map(ma[E].bind(c));d.unshift(b);let e=pa(d.join("|"));
b=`${H}-${e}`;let [f,g]=a[ja](),z=g[K]();c[k]=a=f;z[U]().then(ka.bind(z,b,[]))}}catch(d){}return a}function J(c,a,b){try{let d;switch(a){case 1:d=b;break;case 2:d=JSON.stringify(b);break;case 3:d=V(new Uint8Array(b));break;case 4:d=V(b);break;case 5:d=b[r]().then(J.bind(null,c,1))}if(!R(d)){let e=ea.exec(d??"");w([1229212980,c,e&&(e[1]||d)||null],"/")}}catch(d){}return b}function na(c,a){let b=c;a=a.split(".");if(R(b))if(a[0]=="*"){a.shift();for(let d of Ma(c))try{if(R(b=c[d])&&Na(b,a[0])){for(let e of a)b=
b[e];if(b!==void 0)return b}}catch(e){}}else try{for(let d of a)b=b[d];return b}catch(d){}}function wa(c,a){for(;c&&a--;c=c.parentElement);return c}const Oa=Array.isArray,R=Object.isExtensible,p=globalThis,Pa=window.origin||document.origin||location.origin,w=window.postMessage.bind(window);let ra=0,l,h,ma,V,ua,M,H=0,xa,I,Q,la,ya,N,W,X,P,sa,ta,O,x,k,r,y,K,ia,ha,u,ca,da,za,S,E,ja,U,Y,Z,aa,Aa,oa,G,ea,m,v,q,n,t,A,B,C,D,F;const Na=Object.hasOwn||Function.call.bind(Object.prototype.hasOwnProperty),Ma=Object.getOwnPropertyNames,
Qa=RegExp(" *\\$([<>=]) *");window.addEventListener("message",function(c){var a=c.data;if(Oa(a)&&c.origin==Pa)switch(a.shift()){case 1229212978:var b,d,e;[H,xa,I,Q,la,b,f,d,g,e]=a;if(!b)break;[ya,N,W,X,P,sa,ta,O,x,k,r,y,K,ia,ha,u,ca,da,za,S,E,ja,U,Y,Z,aa,Aa,oa]=b.split("|");if(g)G=RegExp(g),ea=RegExp(e);else var f=d=!1;(b=f)?(l||=p[ya].prototype,m||(m=l[N],l[N]=qa),l[N]!==qa&&(m=null),!v&&m&&(v=l[W],l[W]=Fa),!q&&m&&(q=l[X],l[X]=Ea)):(m&&(l[N]=m,m=null),v&&(l[W]=v,v=null),q&&(l[X]=q,q=null));d?(h||=
p[za].prototype,ma||=p[ha].prototype,V||=TextDecoder.prototype.decode.bind(new TextDecoder("utf-8")),ua||={stream:!0},n||(n=p[O],p[O]=fa),p[O]!==fa&&(n=null,t||(t=h[r],h[r]=va),h[r]===va?(A||(A=h[y],h[y]=Ha),B||(B=h[Z],h[Z]=Ia),C||(C=h[aa],h[aa]=Ja),D||(D=h[Y],h[Y]=Ka),F||(F=Object[Aa](h,k)[E],Object[oa](h,k,{[E]:La}))):t=null)):(n&&(p[O]=n,n=null),t&&(h[r]=t,t=null),A&&(h[y]=A,A=null),B&&(h[Z]=B,B=null),C&&(h[aa]=C,C=null),D&&(h[Y]=D,D=null),F&&(Object[oa](h,k,{[E]:F}),F=null));(b||d)&&w([1229212979,
b?!!m:null,d?!!n:null,d&&!n?!!t:null],"/");break;case 1229212981:let [Ra,Ba,Sa]=a,ba;try{if(Ba?ba=document.querySelector(`[${xa}="${Ba}"]`):ba=window,ba)a:if(c=ba,a=Sa,b=a.split(Qa),b.length>1){for(b.shift();c&&(f=b.shift());){var g=b.shift().trim();for(e=1;g[g.length-e]=="<";e++);--e&&(g=g.slice(0,-e).trim());switch(f){case "<":c=wa(g?c.closest(g):c,e);break;case ">":c=wa(c.querySelector(g),e);break;case "=":if(g=na(c,g),g!==void 0){d=g;break a}}}d=void 0}else d=na(c,a)}catch(Ta){}w([1229212982,
Ra,d],"/");break;case 1229212983:if(d=a[0]){var [z,T,Ca]=d.split("|");if(n){if(M=na(p[z],T))M[Ca]=fa}else M&&(M[Ca]=void 0,M=null)}}},!1);w([1229212977],"/")})();
